name: eHideTags
version: '${version}'
main: ru.enis.ehidetags.Core
api-version: 1.13
author: Enis
description: Plugin to hide players nametags
softdepend: [PlaceholderAPI]

commands:
   eht:
      description: Main Plugin Command
      aliases:
         - ehidetags
         - ehidet
         - ehtags
      usage: /eht

permissions:
   eht.*:
      description: Gives access to all plugin functions
      children:
         eht.reload: true
         eht.command: true
         eht.help: true
         eht.updatenotify: true
         eht.debug: true
         eht.test: true
   eht.reload:
      description: Allows you to reload plugin
      default: op
   eht.test:
      description: Allows you to use /eht test
      default: op
   eht.command:
      description: Allows you to use /eht command
      default: true
   eht.help:
      description: Allows you to use /eht help command
      default: true
   eht.debug:
      description: Allows you to use /eht debug command
      default: op
   eht.updatenotify:
      description: Allow you to get update notifications
      default: op